---
version: "2.0"
services:
  app:
    image: cro7/akash-try-on:0.0.2
    expose:
      - port: 7860
        as: 7860
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 8
        memory:
          size: 32Gi
        storage:
          - size: 40Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        app:
          denom: uakt
          amount: 1000
deployment:
  app:
    dcloud:
      profile: app
      count: 1